### ISSUE TITLE
libmesh v0.9.4 tar.gz file contains superfluous dotfiles

### ISSUE THREAD

**Issue by dmcdougall** [libMesh/libmesh#715] opened 2015-11-10 16:42 UTC
Here's an excerpt from `tar -xvf libmesh-0.9.4.tar.gz`:

```
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.68.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.69.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.69.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.PointFile.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.PointFile.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.an1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.an1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.dfp1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.dfp1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.dfr1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.dfr1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.dfr2.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.dfr2.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.dfr3.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.dfr3.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.gr1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.gr1.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.gr2.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.gr2.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.gr3.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/test.gr3.dmp
libmesh-0.9.4/contrib/netcdf/v4/ncdap_test/expected3/._test.gr4.dmp
```

Hopefully nothing harmful, but thought I'd bring it up.

**Comment by jwpeterson** [comment] 2015-11-10 16:55
Hmm... probably a bug in Netcdf's "make dist".  If so, we would probably wait for upstream to fix it...

**Comment by roystgnr** [comment] 2015-11-10 17:14
Not Netcdf's fault.  We've even got ._Changelog in there.

They're 340 byte binary files, apparently OS X turds:

$ strings libmesh-0.9.4/._ChangeLog 
Mac OS X        
ATTR
/com.apple.metadata:_kTimeMachineNewestSnapshot
/com.apple.metadata:_kTimeMachineOldestSnapshot
bplist003B-c
bplist003A

**Comment by dmcdougall** [comment] 2015-11-10 17:15
It isn't netcdf.  See [here](http://pastebin.com/iEP0tT9u) for the full output.

**Comment by jwpeterson** [comment] 2015-11-12 16:37
I don't currently have and dot-underscore files in my clone, but the release was made under a different version of OSX than I currently have. Perhaps it would be good practice to run "make dist" in a fresh clone rather than one that's been used for development...

**Comment by jwpeterson** [comment] 2015-12-03 20:37
Have a look at the most recent release candidate [tarballs](https://github.com/libMesh/libmesh/releases/tag/v0.9.5-rc1).  I still see the .dmp files (not sure what we can do about that) but I don't see any OSX temporary files, etc.

**Comment by roystgnr** [comment] 2015-12-03 20:43
Are dmp files extraneous?  We've got them checked into git, they're also checked into upstream git, e.g.:

https://github.com/Unidata/netcdf-c/tree/master/ncdap_test/expectremote4

I assumed those were gold standards or expect scripts or something for their regression tests.

**Comment by jwpeterson** [comment] 2015-12-03 20:50
I don't know, @dmcdougall was the one complaining about them so I thought he knew. :confused:

**Comment by jwpeterson** [comment] 2015-12-03 20:54
Oh I see, he was talking about the "._" prefixed versions of the .dmp files, not the .dmp files themselves.  Yeah I'm going to close this issue, I think the problem is fixed by running `make distcheck` from a fresh clone and/or not using whatever version of OSX it was that generated those dot files.

**Closed by jwpeterson** 2015-12-03 20:54 UTC

**Comment by dmcdougall** [comment] 2015-12-03 20:56
You have `*.dmp` files, but all the extraneous `._*.dmp` files are gone.

> @dmcdougall was the one complaining about them

The right to complain is a right every British citizen is endowed with at birth.  I consider myself happy to provide you with such a service and, although I realise you have a myriad of choices, I'd like to thank you for choosing McDougall Complaints® as your primary complaint provider.

**Comment by jwpeterson** [comment] 2015-12-03 20:58
Thanks, I thought your pricing scheme was very reasonable as well.

**Comment by dmcdougall** [comment] 2015-12-03 21:04
You're welcome.  We pride ourselves on our competitive service.  Should you find yourself needing more of our complaints, I recommend speaking to our sales representatives about one of our Loyalty Complaints Plans.  Have a splendid day.
