### ISSUE TITLE
Reduce geometric-based checks for nodes with adaptivity

### ISSUE THREAD

**Issue by permcody** [libMesh/libmesh#436] opened 2015-01-14 16:29 UTC
libMesh tends to collapse nodes that are geometrically close which interferes with XFEM work and or very small elements. We should attempt to use connectivity information in the decision process of determining when nodes are truly duplicates or not. 

Generation of nodes on parallel processors may still require geometric checks.

**Comment by roystgnr** [comment] 2015-03-10 20:38
@dknez just reminded me that we've got a third section of the code where we assume unique node geometry: the libHilbert ordering.

Hopefully @benkirk will correct me, but I believe the *_global_indices() methods will fail in the case where two nodes occupy the same point.

I don't see an easy fix.  My "bracketing nodes" idea in TopologyMap depends on the fact that we can use neighboring nodes for disambiguation... but neighboring node ids aren't canonical enough to give us a partition-independent ordering, and neighboring node Hilbert indices may *themselves* be duplicates in meshes with slits, and it's hard to define "neighboring" in the case of non-child elements in the first place.

We could get the set of active elements which own a node, take the average of their centroids, take the Hilbert key of that, then use *pairs* of Hilbert keys for uniqueness (and dictionary ordering for sorting).  It would be nice to have a solution that doesn't double the amount of communication required, though.

**Comment by dschwen** [comment] 2015-03-10 20:41
The Hilbert index is a key according to which the nodes are sorted before being partitioned. Having two nodes with the same HI should not necessarily result in a failure. I looked at the code a while ago and my memory is a bit foggy. The sorting of nodes with the same HI could be made unambiguous by including the node id in the comparison operation.

**Comment by roystgnr** [comment] 2015-03-10 20:53
For partitioning, the sorting just needs to be "good enough" to hand off to METIS etc.  A slight change here or there makes no difference.  I'm pretty sure having a duplicate Hilbert key currently leads to bugs (that was the proximate cause of the bug that I fixed in #316 IIRC), but we could just fix up the sorting algorithms to handle duplicate keys.

For partition_agnostic restarts, the node id is too ambiguous, though: if we write a mesh on N processors, then read it in on M, the id assigned to a node in the read won't necessarily match the id it had during the write.  We need a completely id-independent ordering to get away with that... and to avoid breaking this functionality in old restart files, it should be a *compatible* id-dependent ordering; i.e. we need to be sorting by (hilbert_key, something_else).

**Comment by dschwen** [comment] 2015-03-10 20:55
Oh, wait, duplicate HI may be a problem because only a list of HI sorted. What follows is a lookup of the nodes by their HI values. With duplicate HI this lookup may fail.

**Comment by roystgnr** [comment] 2015-07-28 18:04
I'm increasingly of the opinion that "something_else" needs to be the unique_id().  In complicated-but-useful cases like meshes with overlapping sections, it's possible that two elements might have the same centroid *and* the same nodal locations *and* the same neighbor centroids ad infinitum.

Using unique_id has some obvious disadvantages (we don't configure with unique_id() by default due to memory expense) and complications (on top of the sorting fixes we'd need to add a "give up with a helpful error message" code path when people use meshes with duplicate-libHilbert-key objects but didn't configure with unique ids) and possible concerns (we only save unique_ids in xdr/xda I/O, but that's the only place we need such perfectly reproduceable ordering so maybe that's okay).  But it seems like the "overlapping locally identical meshes" use case is a counterexample to literally any other possible option.

**Comment by roystgnr** [comment] 2016-02-22 22:00
This was fixed for parallel communication in #719, and for restarts in #768; the last petty issues were fixed in #803.

**Closed by roystgnr** 2016-02-22 22:00 UTC
