### ISSUE TITLE
"Error writing nodeset parameters" with HEAD version

### ISSUE THREAD

**Issue by dknez** [libMesh/libmesh#1430] opened 2017-09-15 20:23 UTC
I just updated to fc1536d4200a43dfa56270caeb107619e2827cea and now I hit the "Error writing nodeset parameters" error in ExodusII_IO_Helper for one of my test models. I'll look into this in more detail, but also wanted to check if anyone has any thoughts on what may have happened?

**Comment by jwpeterson** [comment] 2017-09-15 20:39
I merged 7e83cfcdc yesterday but it passed all the MOOSE testing and should really have only affected infinite elements builds...

**Comment by dknez** [comment] 2017-09-15 20:53
Running in dbg mode gives this error message:

Exodus Library Error: [ex_put_sets]
	Error: failed to define number of entries in node set 130004 in file id 65536
	[-41] netcdf constraint NC_MAX_DIMS exceeded
Error writing nodeset parameters

**Comment by jwpeterson** [comment] 2017-09-15 20:58
OK... and if you revert 7e83cfcdc it goes away? I really don't see how my change could have broken nodeset writing. 

Has it been a while since you updated? We also upgraded the version of NetCDF that we bundle with libmesh somewhat recently (April 2017). If so, maybe try a clean build.

**Comment by dknez** [comment] 2017-09-15 21:04
I updated from 96532f4d070713c5c452fe150a589c0af36d9554 from August 23, so it hasn't been very long. I'll try reverting 7e83cfc and I'll also try a clean build and see what happens.

Also, I see there is some discussion about this issue, and it's relation to pre-installed packages:
https://github.com/Unidata/netcdf-c/issues/148

**Comment by dknez** [comment] 2017-09-15 22:31
Reverting 7e83cfc didn't help, and neither did doing a clean build... I'll have to look further. I guess it's something to do with the NetCDF version I'm linking to, or something. Not sure what changed for me to trigger this issue, though.

**Comment by jwpeterson** [comment] 2017-09-15 23:23
Yeah if I recall correctly, Ben had to change the default values of some constants in NetCDF when he vendored in the new version. It's likely that you can't use a vanilla NetCDF with libmesh because of this...

**Comment by dknez** [comment] 2017-09-16 02:10
Well I still haven't figured out what's going wrong. As far as I can tell based on config log I'm using contrib/netcdf, and I reverted to the libMesh version that I was using before, and I still get the same error.

It's almost certainly a problem with my configuration somehow, not a libMesh issue, so I will close this issue. But @jwpeterson if you do have any other suggestions on what I could try in order to get to the bottom of this, let me know :)

**Closed** 2017-09-16 02:11 UTC

**Comment by jwpeterson** [comment] 2017-09-17 02:37
Can you run ldd (otool -L on MacOS) on the shared lib for your build? Make sure you have something like the following:
```
/Users/petejw/projects/libmesh_git/installed/lib/libnetcdf.11.dylib (compatibility version 12.0.0, current version 12.4.0)
```
for libnetdf, and not something in /usr/lib on your system.

**Comment by dknez** [comment] 2017-09-17 18:45
I get:

```
libnetcdf.so.11 => /home/dknez/software/libmesh_install/opt_real/libmesh/lib/libnetcdf.so.11 (0x00007f3e6c013000)
```

That looks correct to me, and I still get the error mentioned above. Ugh. I'll see if I can come up with a minimal test case for this.

**Comment by jwpeterson** [comment] 2017-09-17 20:35
Yep, I agree it looks correct. 

I wonder if you have another netcdf.h in your list of compiler include paths. Since we suspect the problem is related to a #define, maybe that it is a header thing instead of a lib thing.

**Comment by dknez** [comment] 2017-09-18 01:11
Actually, according to ldd my app is linking to "/usr/lib/x86_64-linux-gnu/libnetcdf.so.11", even though libMesh is linking to the contrib version of netcdf, so I should just have to fix up my build script for my app.

Thanks for your help.

**Comment by jwpeterson** [comment] 2017-09-18 01:15
Nice, glad you figured it out!

**Comment by dknez** [comment] 2017-09-18 17:19
@jwpeterson so the issue is that we use a python script to build our app codes, and we use "libmesh-config --libs" to get the lib info from libMesh within that script. It turns out that this command lists "-L/usr/lib/x86_64-linux-gnu" (where the system netcdf library is stored) before it lists "-L/home/dknez/software/libmesh_install/opt_real/libmesh/lib", and as a result the linker preferentially linked to the system netcdf library.

Our fix was to prepend "-L/home/dknez/software/libmesh_install/opt_real/libmesh/lib" to the output of "libmesh-config --libs", which fixes the issue for me. Does that sound reasonable to you, or would you deal with this in a different way?

Thanks,
David

**Comment by jwpeterson** [comment] 2017-09-18 19:00
@dknez I'm a little surprised that this is still happening, since I did some work a while back in the `contrib/bin/strip_dup_libs.pl` script to force the system library paths, like `/usr/lib` in your example, to the end of the link line. It this isn't happening for you, there may be a bug in that perl script. Can you send me (off-list if necessary) the full output of `libmesh-config --libs` on your system?

**Comment by dknez** [comment] 2017-09-18 19:05
OK, I sent it to your gmail account.

**Comment by jwpeterson** [comment] 2017-09-18 19:19
Hmm... the problem seems to be that the system paths are at the end of the link line *except for* the path to `$INSTALLED_LIBMESH/lib`, which might be outside the purview of the `strip_dup_libs.pl` script entirely. (I see the same thing on my system, by the way.) 

This fix worked in the past for ensuring that e.g. an MPI in `/opt` got linked in before an MPI in `/usr/lib`, but it is not sufficient to fix your particular case, since the library in question is in `$INSTALLED_LIBMESH/lib`.

Maybe we can we just move `$INSTALLED_LIBMESH/lib` to the beginning of the list of libs without breaking anything else? I'll take a closer look at how this works...

**Comment by dknez** [comment] 2017-09-18 19:29
OK, thanks for looking into it.
