### ISSUE TITLE
Cannot use multiple composite boundaries from gmsh in conversion to exodus

### ISSUE THREAD

**Issue by lindsayad** [libMesh/libmesh#1252] opened 2017-02-21 19:30 UTC
Here's the relevant excerpt of a gmsh script:
```
bound_surfs = {};
bound_surfs[] = fuel_surfaces[];
bound_surfs += moder_surfaces[];
bound_surfs += fuel_tops[];
bound_surfs += moder_tops[];
bound_surfs += fuel_sides[];

temp_diri_surfs = {};
temp_diri_surfs[] = fuel_surfaces[];
temp_diri_surfs += moder_surfaces[];
temp_diri_surfs += fuel_sides[];

temp_outflow_surfs = {};
temp_outflow_surfs[] = fuel_tops[];

temp_inflow_surfs = {};
temp_inflow_surfs[] = fuel_surfaces[];

Physical Surface ("boundary") = { bound_surfs[] };
// Physical Surface ("temp_diri_bnd") = { temp_diri_surfs[] };
// Physical Surface ("temp_outflow_bnd") = { temp_outflow_surfs[] };
// Physical Surface ("temp_inflow_bnd") = { temp_inflow_surfs[] };
// Physical Surface ("fuel_bottoms") = { fuel_surfaces[] };
// Physical Surface ("fuel_tops") = { fuel_tops[] };
// Physical Surface ("moder_bottoms") = { moder_surfaces[] };
// Physical Surface ("moder_tops") = { moder_tops[] };
// Physical Surface ("fuel_sides") = { fuel_sides[] };
```
Paraview visualization of "boundary" sideset after conversion to exodus (this is what it should look like):

![complete_boundary](https://cloud.githubusercontent.com/assets/10248304/23181110/4450d878-f839-11e6-9ba3-056563103175.png)

Now uncomment next three lines:
```
Physical Surface ("boundary") = { bound_surfs[] };
Physical Surface ("temp_diri_bnd") = { temp_diri_surfs[] };
Physical Surface ("temp_outflow_bnd") = { temp_outflow_surfs[] };
Physical Surface ("temp_inflow_bnd") = { temp_inflow_surfs[] };
```
 and visualize "boundary" sideset again:

![broken_boundary](https://cloud.githubusercontent.com/assets/10248304/23181145/70754bbe-f839-11e6-9206-db3aa8effb21.png)

I can work around this by just using individual pieces of the volume surface, e.g. these boundary definitions:
```
Physical Surface ("fuel_bottoms") = { fuel_surfaces[] };
Physical Surface ("fuel_tops") = { fuel_tops[] };
Physical Surface ("moder_bottoms") = { moder_surfaces[] };
Physical Surface ("moder_tops") = { moder_tops[] };
Physical Surface ("fuel_sides") = { fuel_sides[] };
```
but it would nice to be able to use the composites. I'll attach the full `gmsh` script in case anyone wants to play around with it.

[msre_cuboid.txt](https://github.com/libMesh/libmesh/files/791261/msre_cuboid.txt)

**Comment by jwpeterson** [comment] 2017-02-21 19:37
So uncommenting those lines caused the sidesets to "shrink" down to the flat surfaces shown?  Do you suspect the problem is in the Gmsh reader?  I.e. if you query the `boundary_info` object on the Mesh after reading in the Gmsh file, does it have all the sidesets you expect it to have?  Would you mind also linking the .msh file which gets generated from your script?

**Comment by lindsayad** [comment] 2017-02-21 20:01
Yes, all the sidesets are listed in paraview:

![sideset_names](https://cloud.githubusercontent.com/assets/10248304/23182129/0b7e3faa-f83d-11e6-83dc-b2213f63d5d2.png)

It seems like if an individual surface is used in a later physical surface definition, then it does not appear in the previous physical surface definition. So last physical surface to be defined (`temp_inflow_bnd`) appears as it should:

![temp_inflow_bnd](https://cloud.githubusercontent.com/assets/10248304/23182232/709fb1c0-f83d-11e6-9ded-a962abf8a7e4.png)

So does the second to last physical surface `temp_outflow_bnd` which shares no surfaces with `temp_inflow_bnd`:

![temp_outflow_bnd](https://cloud.githubusercontent.com/assets/10248304/23182257/8723e042-f83d-11e6-861d-833aca6f407e.png)

However, `temp_diri_bnd`, which should have **all** the side and bottom surfaces, has the surfaces that also belong to `temp_inflow_bnd` missing:

![temp_diri_bnd](https://cloud.githubusercontent.com/assets/10248304/23182299/b410c4c6-f83d-11e6-812e-a58b470de64a.png)

Finally, the physical surface which was the first to be defined, `boundary`, which should encapsulate the boundary of the entire cuboid, has all the surfaces shared with the other three physical surfaces missing.

![boundary](https://cloud.githubusercontent.com/assets/10248304/23182341/d6ffd35a-f83d-11e6-9cc2-b1350f6d2eef.png)

Attaching `msh` file (change txt to msh):

[test_moose_read.txt](https://github.com/libMesh/libmesh/files/791354/test_moose_read.txt)

I would guess the problem is in the reader, but I would have to dive into the source code I think to test that hypothesis

**Comment by jwpeterson** [comment] 2017-02-21 20:19
Quick thought off the top of my head: Are there lower-dimensional elements (2D elements) in your 3D mesh? Elements in libmesh can only belong to a single subdomain, whereas sides of elements can be members of as many sidesets as you want.

If you have lower-dimensional elements which belong to multiple Physical sets, only the last one applied will actually "stick"... that might cause what you are seeing here?

**Comment by lindsayad** [comment] 2017-02-21 20:32
That was a very helpful comment...this isn't a libmesh issue at all. Gmsh only supports one physical ID tag, so that explains exactly what I was seeing...as it works for libmesh only the last physical tag in gmsh "sticks."

**Comment by lindsayad** [comment] 2017-02-21 20:45
Got a little ahead of myself...remembered that when I visualized the mesh using the `gmsh` GUI, all of the physical surfaces were complete. I realize that this is accomplished by creating surface (2D) elements in triplicate on the bottom surface for instance; see excerpt from element list in `msh` file:
```
1 2 2 3 11 105 120 4
2 2 2 4 11 105 120 4
3 2 2 6 11 105 120 4
```
So does libmesh remove "duplicate" elements? Because if it did not, then having triplicate 2D elements would avoid the issue of only being able to do one-to-one element-to-subdomain?

**Comment by jwpeterson** [comment] 2017-02-21 21:16
> So does libmesh remove "duplicate" elements? Because if it did not, then having triplicate 2D elements would avoid the issue of only being able to do one-to-one element-to-subdomain. Or is the one-to-one analogy invalid for mapping lower-dimension elements to sidesets?

The default is for libmesh to use lower-dimensional elements in Gmsh files to specify boundary conditions -- so 3 copies of the same lower-dimensional element with different IDs *should* do the right thing for you.  

There is also the possibility for lower-dimensional elements to be read in as *actual* elements that are kept around in the libmesh mesh... I don't think this is what you are after in the present case, though.

**Comment by lindsayad** [comment] 2017-02-21 21:22
Correct, I would like the former. So it sounds like I *should* be getting what I want...but I'm not.

**Comment by jwpeterson** [comment] 2017-02-21 21:33
OK, the bug is probably in libmesh's Gmsh reader then.  Maybe I never actually tested the case of multiple lower-dimensional elements specifying multiple sideset ids for the same side... I will try to take a look tonight if I get a chance.

**Comment by lindsayad** [comment] 2017-02-21 21:36
No worries if you don't get to it quickly. It's not urgent since I can easily just use the non-composite boundaries.

**Comment by jwpeterson** [comment] 2017-02-21 21:37
Aha, yeah, the bug is on line 601 of gmsh_io.C:
```
// We only allow one match, so break out of for loop.
break;
```

You could actually just try removing this break and see if it fixes the issue.

**Comment by jwpeterson** [comment] 2017-02-21 21:39
If that works, I will make a patch... some of the documentation around this section of code should be fixed up a bit as well.

**Comment by lindsayad** [comment] 2017-02-21 22:20
Sure enough, just commenting out that line fixed the issue.

**Comment by jwpeterson** [comment] 2017-02-21 22:21
Haha, OK, thanks for confirming.

**Closed** 2017-02-22 21:53 UTC
